title: MySpace Blog
description: A blog about myspace
url: "https://harisibrahimkv.github.io"
baseurl: "/myspace"
permalink: /:title/

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed