name: Build and Deploy Jekyll site

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install

    - name: Debug - Show Jekyll version and configuration
      run: |
        bundle exec jekyll --version
        bundle exec jekyll doctor
        cat _config.yml

    - name: Build site
      run: JEKYLL_ENV=production bundle exec jekyll build --trace

    - name: Debug - List directory contents
      run: |
        echo "Current directory:"
        pwd
        echo "Contents of current directory:"
        ls -la
        echo "Contents of _site directory (if it exists):"
        ls -la _site || echo "_site directory not found"
        echo "Contents of docs directory (if it exists):"
        ls -la docs || echo "docs directory not found"

    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/master'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
        publish_branch: gh-pages

    - name: Upload artifact for preview
      if: github.event_name == 'pull_request'
      uses: actions/upload-artifact@v4
      with:
        name: site-preview
        path: ./_site