name: Build and Deploy Jekyll site

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install

    - name: Debug - Show Jekyll configuration
      run: |
        echo "Jekyll version:"
        bundle exec jekyll --version
        echo "Jekyll configuration:"
        bundle exec jekyll build --trace --config _config.yml --verbose

    - name: Build site
      run: JEKYLL_ENV=production bundle exec jekyll build --verbose

    - name: List _site contents
      run: |
        echo "Contents of _site directory:"
        ls -R _site

    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/master'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
        publish_branch: gh-pages
        force_orphan: true

    - name: Debug deployment
      if: github.ref == 'refs/heads/master'
      run: |
        git fetch origin gh-pages
        echo "Contents of gh-pages branch:"
        git ls-tree -r --name-only origin/gh-pages

    - name: Upload artifact for preview
      uses: actions/upload-artifact@v4
      with:
        name: site-preview
        path: ./_site